In [1]:
import numpy as np

In [2]:
an_array=np.array([3,33,333]) #create a rank 1 array
print(type(an_array)) #the type of anndarray is:"<class 'numpy.ndarray.'>


<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [5]:
an_array[0]=888
print(an_array)

[888  33 333]


In [6]:
another=np.array([[11,12,13],[21,22,23]]) #create a rank two array
print(another)
print("the shape is 2rows,3columns:",another.shape) #rows*columns
print("Accessing elements[0,0],[0,1],and[1,0]of the ndarray:",another[0,0],",",another[0,1],",",another[1,0])

[[11 12 13]
 [21 22 23]]
the shape is 2rows,3columns: (2, 3)
Accessing elements[0,0],[0,1],and[1,0]of the ndarray: 11 , 12 , 21


In [7]:
#create 2*2 array of zeros
ex1=np.zeros((2,2))
print(ex1)


[[0. 0.]
 [0. 0.]]


In [8]:
#create a2*2 array filled with 9,0
ex2=np.full((3,3),9.0)
print(ex2)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [9]:
ex3=np.eye(2,2) #create a 2*2 matrix the diagonal is 1 and other are zero
print(ex3)

[[1. 0.]
 [0. 1.]]


In [10]:
ex4=np.ones((2,1))  #create a array of ones
print(ex4)

[[1.]
 [1.]]


In [11]:
#which means we need to use two indexes to access an element
print()    # []DECLARE POSITION
print(ex4[0,0])


1.0


In [12]:
print(ex4.shape)

(2, 1)


In [13]:
# crate an array of random floots bet 0and1
ex5=np.random.random((2,2))
print(ex5)

[[0.64821623 0.2149509 ]
 [0.44956892 0.80502128]]


In [14]:
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [15]:
# use array slicing to get a subarray consisting of the first 2ro*2 column
a_slice=an_array[0:2,1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [16]:
#when you modify a slice , you actullu modify the understanding array
print("Before:",an_array[0,1]) # inspect the element at 0,1
a_slice[0,0]=1000 #a slice 0,0 is the same piece of data as an array[0,1]
print("After:",an_array[0,1])

Before: 12
After: 1000


In [17]:
a_slice1=an_array[1,:]
print(a_slice1)


[21 22 23 24]


In [18]:
a_slice2=an_array[1:2,0:]
print(a_slice2)

[[21 22 23 24]]


In [19]:
print(a_slice1.shape)

(4,)


In [20]:
print(a_slice2.shape)

(1, 4)


In [21]:
row_rank1=an_array[1,:]
print(row_rank1,row_rank1.shape)

[21 22 23 24] (4,)


In [22]:
row_rank2=an_array[1:2,:]
print(row_rank2,row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [23]:
colunm_rank1=an_array[:,1]
print(colunm_rank1,colunm_rank1.shape)

[1000   22   32] (3,)


In [24]:
col_rank2=an_array[:,1:2]
print(col_rank2,col_rank2.shape)

[[1000]
 [  22]
 [  32]] (3, 1)


In [25]:
an_array=np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print('original Array:')
print(an_array)
                  
            

original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [26]:
col_indices=np.array([0,1,2,0])
print('\nCol indices picked:',col_indices)
row_indices=np.arange(4)#0,1,2,3
print('\nRows indices picked:',row_indices)


Col indices picked: [0 1 2 0]

Rows indices picked: [0 1 2 3]


In [27]:
for i,j in zip(row_indices,col_indices):
    print(i,",",j)
    '''for i in row indices, for j in col indices'''

0 , 0
1 , 1
2 , 2
3 , 0


In [28]:
#select one element from each row
print('value in the array at those indices:',an_array[row_indices,col_indices])
#an_array[0,0],[1,1][2,1][2,2][3,0]- an array{row_indices,col_indices}

value in the array at those indices: [11 22 33 41]


In [29]:
#change one ele from each row using the indices selected
an_array[row_indices,col_indices]+=10000 #+= mean a=a+10 is same as a+=10
print('\nChanged Array:')
print(an_array)


Changed Array:
[[10011    12    13]
 [   21 10022    23]
 [   31    32 10033]
 [10041    42    43]]


# Boolean Indexing

In [30]:
import numpy as np

In [31]:
#create a3*2 array
an_array=np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [32]:
#crate a filter which will be boolean values for whether each element meet this condition
filter=(an_array>15)
filter


array([[False, False],
       [ True,  True],
       [ True,  True]])

In [33]:
#we cn now select just those element which meet that criteria
print(an_array[filter])#value that are greter than 15

[21 22 31 32]


In [34]:
print(an_array>15)

[[False False]
 [ True  True]
 [ True  True]]


In [35]:
#for short, we could have just used the aproach below without the need for the separate filter array
an_array[an_array>15]

array([21, 22, 31, 32])

what is particularly useful is that we can actully change element in the array applying asimilar logical filter. lets add 100 all the even values

In [36]:
an_array[an_array%2==0]+=100#a+=100 is same as a=a+100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [37]:
ex1=np.array([11,12])#python assign the datatype
print(ex1.dtype)

int32


In [38]:
ex2=np.array([11.0,12.0])#python assign the datatype
print(ex2.dtype)

float64


In [39]:
ex3=np.array([11,12],dtype=np.int64)#you can also tellpython the datatype
print(ex3.dtype)

int64


In [40]:
#you cn use this to force float into integer (using floor function)
ex4=np.array([11.1,12.7],dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [41]:
#you czn use this to force integer to float if you anticipate
#the values may change to floor later
ex5=np.array([11,21],dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


In [42]:
import numpy as np
x=np.array([[111,112],[121,122]],dtype=np.int)
y=np.array([[211.1,212.1],[221.1,222.1]],dtype=np.float64)
print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [43]:
#add
print(x+y)#plus sign works
print()
print(np.add(x,y))#so does the numpy function 'add'

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [44]:
#subtract
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [45]:
#multiply
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [46]:
#divide
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [47]:
#square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [48]:
#exponent(e**x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [49]:
#setup arandom 2*5 matix
arr=10*np.random.randn(2,5) #random.random or random.randn or random.randint
print(arr)


[[  6.54504309  26.59604997  -0.49876747  -0.28276004  -0.06153474]
 [ -5.6954781   -3.75843584  -0.50425476 -17.66057067   9.01528025]]


In [50]:
#compute the mean for all elements
print(arr.mean())

1.3694571686955512


In [51]:
#compute the mean by row
print(arr.mean(axis=1))

[ 6.45960616 -3.72069183]


In [52]:
#compute the mean by column
print(arr.mean(axis=0))

[ 0.4247825  11.41880706 -0.50151112 -8.97166535  4.47687275]


In [53]:
#sum all the elements
print(arr.sum())

13.694571686955513


In [54]:
#compute the medians
print(np.median(arr,axis=1)) #by rows 1st and 2nd also


[-0.06153474 -3.75843584]


In [55]:
# create a 10 element array of randoms
unsorted=np.random.randn(10)
print(unsorted)

[ 0.58367331 -1.15013129 -0.01630546  1.09062623 -1.49087623  1.02317083
 -1.07104477  0.80129984 -0.85356004 -0.0394733 ]


In [56]:
#create copy and sort
sorted=np.array(unsorted)
sorted.sort()  #it will arrange values in ascending order i.e sorting
print(sorted)
print()
print(unsorted)

[-1.49087623 -1.15013129 -1.07104477 -0.85356004 -0.0394733  -0.01630546
  0.58367331  0.80129984  1.02317083  1.09062623]

[ 0.58367331 -1.15013129 -0.01630546  1.09062623 -1.49087623  1.02317083
 -1.07104477  0.80129984 -0.85356004 -0.0394733 ]


In [57]:
#inplace sorting
unsorted.sort()
print(unsorted)

[-1.49087623 -1.15013129 -1.07104477 -0.85356004 -0.0394733  -0.01630546
  0.58367331  0.80129984  1.02317083  1.09062623]


# findind a unique value

In [58]:
array=np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))#it will return unique values

[1 2 4]


In [60]:
p=int(input("number of item"))
n=int(input("number of boxes contain 5 item"))
k=int(input("number of boxes contin 1 item"))
z=p//5
a=p-(z*5)
if z+a==n+k:
    print(z+a)
elif z+a!=n+k:
    print("we do not have enough value")

number of item15
number of boxes contain 5 item5
number of boxes contin 1 item3
we do not have enough value


In [61]:
15%2#if we are dividing 15 by 2 remainder is 1 (% is mod)

1

In [62]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [63]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [64]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [93]:
print(np.setdiff1d(s2,s1))  #element ins1 that are not in s2

['lamp']


In [66]:
print(np.in1d(s1,s2))#which element of s1 that are not ins2

[False  True  True]


In [67]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [68]:
#create a rank 1 ndarray with 3 values
add_rows=np.array([1,0,2])
print(add_rows)

[1 0 2]


In [69]:
y=start+add_rows #add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [70]:
#create an ndarray which is 4*1 to broadcast across columns
add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [71]:
#ADD To each column of 'start'using broadcasting
y=start+add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [72]:
#this will just broadcast in both dimensions 
add_scalar=np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


example from the slides:

In [73]:
#create our 3*4 matrix
arrA=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
#create our 4*1 array
arrB=[0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [75]:
from numpy import arange
from timeit import Timer
size=1000000
timeits=1000

In [76]:
#create the ndarray with values 0,1,2,.....,size-1
nd_array=arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [77]:
#timer expect the operation as a parameter
#here we pass nd_array.sum()
timer_numpy=Timer("nd_array.sum()","from __main__ import nd_array")
print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000719 seconds


In [78]:
#create the list with value 0,1,2...,size-1
a_list=list(range(size))
print(type(a_list))

<class 'list'>


In [79]:
#timer expects the operation as a parameter, here we pass sum(a_list)
timer_list=Timer("sum(a_list)","from __main__ import a_list")
print("Time taken by list: %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list: 0.042274 seconds


Read or write to Disk:

In [80]:
import numpy as np
x=np.array([23,23,24,24])

In [81]:
np.save('an_array',x)#saves the value in x to an_array

In [82]:
np.load('an_array.npy')#

array([23, 23, 24, 24])

Text Format:

In [83]:
np.savetxt('array.txt',X=x,delimiter=',')#savetxt function will store your file in text format
np.loadtxt('array.txt',delimiter=',')#delimiter and sep are same which is separated by comma,

array([23., 23., 24., 24.])

dot product on matrices and inner product on vectors:

In [84]:
#determine the dot product of two matrices
x2d=np.array([[1,1],[1,1]])
y2d=np.array([[2,2],[2,2]])
print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [85]:
#determine the inner product if two matrices
a1d=np.array([9,9])
b1d=np.array([10,10])
print(a1d.dot(b1d))
print()
print(np.dot(x2d,a1d))

180

[18 18]


In [86]:
#dot product  on an array and vector
x2d=np.array([9,9])     #[1*9+1*9,1*9+1*9]=[18 18]
a1d=np.array([[1,1],[1,1]])
print(x2d.dot(a1d))
print()
print(np.dot(x2d,a1d))

[18 18]

[18 18]


In [87]:
#sum
#sum element in the array
ex1=np.array([[11,12],[21,22]])
print(np.sum(ex1))#add all members

66


In [88]:
print(np.sum(ex1,axis=0)) #columnwise sum


[32 34]


In [89]:
print(np.sum(ex1,axis=1))#row wise sum

[23 43]


In [90]:
#random array
x=np.random.randn(8)
x

array([-0.7246595 ,  1.10862748, -0.55112292, -0.18595312, -0.48443358,
       -0.9254183 ,  0.72574452, -0.67334328])

In [91]:
y=np.random.randn(8)
y

array([-1.24778103,  0.7990048 ,  3.01048059,  0.51686016, -2.3886749 ,
       -0.26525967, -0.42770773, -0.69988711])

In [1]:
#returns element wise maximum between two arrays
import numpy as np
x=np.random.randn(8)
y=np.random.randn(8)
np.maximum(x,y)
print(x)
print(y)
np.maximum(x,y)

[-0.63171222  0.85276808 -0.92484183 -0.98376412 -1.14432932  0.61138018
  1.78747822  1.44134751]
[-0.93978361 -0.35199205 -0.1104564   0.04049335 -0.44938553  0.3081939
 -0.62015868 -0.18047576]


array([-0.63171222,  0.85276808, -0.1104564 ,  0.04049335, -0.44938553,
        0.61138018,  1.78747822,  1.44134751])

RESHAPING ARRAY

In [2]:
#GRAB VALUES FROM 0 through 19 in an array
arr=np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
#reshape to be a4*5 matrix
arr.reshape(4,5)#5,4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
#traspose
ex1=np.array([[11,12],[21,22]])
ex1.T

array([[11, 21],
       [12, 22]])

indexing using where()

In [5]:
x_1=np.array([1,2,3,4,5])
y_1=np.array([11,22,33,44,55])
#where we have true in filter it will print x1 value and for falsey_1 value
#this is the working of .where function
filter=np.array([True,False,True,False,True])

In [6]:
out=np.where(filter,x_1,y_1)
print(out)

[ 1 22  3 44  5]


In [7]:
mat=np.random.rand(5,5)
mat

array([[0.77415645, 0.7111458 , 0.25676756, 0.56596077, 0.75594144],
       [0.63490461, 0.96213778, 0.25980917, 0.88197317, 0.57097004],
       [0.6006708 , 0.46483695, 0.70624023, 0.26266776, 0.48811355],
       [0.82547951, 0.6161795 , 0.4024865 , 0.63722801, 0.21137727],
       [0.10838337, 0.98023894, 0.60985291, 0.74109257, 0.96238381]])

In [8]:
np.where(mat>0.5,1000,-1)
#if mat>0.5 replace(1000) else replace(-1)

array([[1000, 1000,   -1, 1000, 1000],
       [1000, 1000,   -1, 1000, 1000],
       [1000,   -1, 1000,   -1,   -1],
       [1000, 1000,   -1, 1000,   -1],
       [  -1, 1000, 1000, 1000, 1000]])

any or all conditionals

In [9]:
arr_bools=np.array([True,False,True,True,False])

In [10]:
arr_bools.any() #is any value True

True

In [11]:
arr_bools.all()  # are all value true

False

In [12]:
import numpy as np
Y=np.random.normal(size=(1,5))
print(Y)

[[-0.56388124  0.80267307 -0.98043302  0.22122318 -1.54569028]]


In [13]:
Z=np.random.randint(low=2,high=50,size=4)#int integer values
print(Z)#low for lower limit and high for higher limit

[17 47 11 42]


In [14]:
np.random.permutation(Z)#return a new ordering of element inZ

array([11, 42, 47, 17])

In [15]:
np.random.uniform(size=4)# uniform distribution

array([0.80545324, 0.24768425, 0.50924613, 0.28565143])

In [16]:
np.random.normal(size=4)# normal distribution

array([ 2.27309325e-01, -1.31302960e-04, -6.34061151e-01, -1.15453656e+00])

In [17]:
k=np.random.randint(low=2,high=50,size=(2,2))
print(k)

print()
M=np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[14 25]
 [ 4 15]]

[[11 43]
 [29 12]]


In [18]:
np.vstack((k,M)) #join vertically

array([[14, 25],
       [ 4, 15],
       [11, 43],
       [29, 12]])

In [19]:
np.hstack((k,M))#join horizontally

array([[14, 25, 11, 43],
       [ 4, 15, 29, 12]])

In [20]:
np.concatenate([k,M],axis=0)

array([[14, 25],
       [ 4, 15],
       [11, 43],
       [29, 12]])

In [21]:
np.concatenate([k,M.T],axis=1)

array([[14, 25, 11, 29],
       [ 4, 15, 43, 12]])